---
apiVersion: v1
kind: Namespace
metadata:
  name: demos-dev
  labels:
    app.kubernetes.io/managed-by: Helm
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: demos-dev-sa
  namespace: demos-dev
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demos-dev-role
  namespace: demos-dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demos-dev-rolebinding
  namespace: demos-dev
subjects:
  - kind: ServiceAccount
    name: demos-dev-sa
    namespace: demos-dev
roleRef:
  kind: Role
  name: demos-dev-role
  apiGroup: rbac.authorization.k8s.io
---

kind: Secret
apiVersion: v1
metadata:
  name: registry-credentials
  namespace: demos-dev
data:
  .dockerconfigjson: >-
    token_test
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: firebase-config
  namespace: demos-dev-test
data:
  test-cfg.json: |
    {
      "type": "service_account",
      "project_id": "",
      "private_key_id": "",
      "private_key": "",
      "client_email": "",
      "client_id": "",
      "auth_uri": "",
      "token_uri": "",
      "auth_provider_x509_cert_url": "",
      "client_x509_cert_url": "",
      "universe_domain": ""
    }